plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}
android {
    namespace 'vi.com.warning.traffic.shared'
    compileSdk 36

    defaultConfig {
        minSdkVersion 28
        targetSdkVersion 36

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildToolsVersion '36.0.0'
}
dependencies {
    implementation libs.androidx.media
}